### ISSUE TITLE
Time Series danych z podanego przedziału czasu

### ISSUE THREAD

**Issue by kacperklusek** [AtmosFears/AtmosFears-FE#5]
W ramach taska należy przygotować widok który:
- umożliwia wybór zakresu dat z jakiego mają pochodzić dane
- wysyła zapytanie do serwera o dane pochodzące z podanego okresu
- wyświetla otrzymane z serwera dane w postaci wykresu Time Series (poziom zanieczyszczenia vs. czas)

Dla każdego typu zanieczyszczeń powinniśmy wyświetlić osobny wykres.

Do wyboru dat należy wykorzystać taki sam picker jak [w tym issue](https://github.com/AtmosFears/AtmosFears-FE/issues/4) (jeśli już istnieje) aby widoki były w jednym stylu

**Comment by kosmydel** [comment]
Wstępny draft widoku TimeSeries. Przygotowałem prostego forma, który wysyła parametry na razie na mockowy serwer, i wyświetla jakiś prosty wykres z wczytanych danych.
<img width="1035" alt="Zrzut ekranu 2023-05-4 o 16 25 50" src="https://user-images.githubusercontent.com/104823336/236237710-3bb99bc7-2a7e-4e5b-bb5d-1b68c3cb9c09.png">
